### PR TITLE
v17 update

### LINKED ISSUE #1692: Nextcloud - check for exit code of `turnkey-occ user:resetpassword admin`
It appears that [Nextcloud checks the password](https://www.turnkeylinux.org/comment/50716#comment-50716). If the password set doesn't meet the Nextcloud requirements, then the password setting will fail. However, under most circumstance (when run via inithooks), the user will likely miss the error message.

So within the inithook, we should check the exit code and if non-zero, ask user to re-enter password.

The only complicating factor is that we can only error and get the user to try again when running interactively. When running non-interactively, we need to just log the error.

### PR DESCRIPTION
**Pull request by OnGle**
closes https://github.com/turnkeylinux/tracker/issues/1692
part of https://github.com/turnkeylinux/tracker/issues/1767

### CODE REVIEW

**Review by Christie018 — APPROVED** [review]
The changes to nextcloud to update the appliance and the password code looks good to me. I would ensure the password function still allows for the admin to login with creds set at initial install. This was the only thing I got stuck on.

**Comment by JedMeister** [comment]
The only thing that occurs to me is that if launched via the Hub, there is a risk that the password set will fail and the inithooks will hang. We need to at least allow it to fail gracefully when preseeded.

I have merged this regardless and will open a new issue to track that.

**Comment by JedMeister** [comment]
New issue: https://github.com/turnkeylinux/tracker/issues/1773

**Review by Christie018 — COMMENTED** [review]
Changes to finish the update for the next cloud appliance and it's dependencies look good to me. Additionally, the code revisions for this PR add the php-bcmath to plan/main and finish formatting nextcloud.py file to correctly check for password requirements on VM builds. 
The only thing I would discuss further would be if we would want to publish the appliance update to the website without more testing on hub builds.

**Pull request merged**
